import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox'] });
const sleep = ms => new Promise(r => setTimeout(r, ms)); const errs = [];
const p = await b.newPage(); await p.setViewport({ width: 1360, height: 900 }); p.on('pageerror', e => errs.push('PAGEERROR ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); }); p.on('dialog', d => d.accept());
const base = 'http://127.0.0.1:8801/'; const txt = s => p.$eval(s, e => e.innerText.replace(/\s+/g, ' ').trim()).catch(() => '(missing)');
const click = async s => { await p.click(s); await sleep(250); }; const go = async h => { await p.evaluate(x => { location.hash = x; }, h); await sleep(400); };
await p.goto(base + '#/overview', { waitUntil: 'load' }); await p.evaluate(() => localStorage.clear()); await p.reload(); await sleep(1500);
console.log('mode ->', await txt('#mode'), '| running cards:', (await p.$$('.g3 .card')).length);
await go('#/new'); await p.type('#w-name', 'Offer two time slots'); await click('#w-next'); await click('#w-next'); await click('#w-next'); await click('#w-next');
await p.$eval('#w-days', e => { e.value = 7; e.dispatchEvent(new Event('change')); }); await sleep(300); await click('#w-next');
await p.click('[data-preset="win"]'); await sleep(200); await p.$eval('#w-seed', e => { e.value = 11; });
await click('#w-launch'); await p.waitForFunction(() => location.hash.startsWith('#/live/'), { timeout: 20000 }); await sleep(600);
console.log('launched ->', (await txt('h1')).slice(0, 40), '|', (await txt('.page-head .sub')).slice(0, 90));
for (let i = 0; i < 7; i++) { if (await p.$('#a-adv')) await click('#a-adv'); }
console.log('result ->', (await txt('.banner')).slice(0, 110)); await p.screenshot({ path: '/tmp/canary_shots/live_launched.png', fullPage: true });
await go('#/new'); await p.evaluate(() => { WZ = null; DYN.ui.wizard = null; }); await go('#/new'); await p.type('#w-name', 'Full prompt test'); await click('#w-next'); await click('[data-mode="full"]'); await click('#w-load');
await p.evaluate(() => { const t = document.querySelector('#w-full'); t.value = t.value.replace('buyer name = 3', 'buyer name = 2'); t.dispatchEvent(new Event('input')); }); await sleep(300);
console.log('full prompt diff rows ->', (await p.$$('#w-diff .diff div')).length, '| vars:', (await txt('#w-vc')).slice(0, 50));
for (let i = 0; i < 4; i++) await click('#w-next'); await click('#w-launch'); await p.waitForFunction(() => location.hash.startsWith('#/live/'), { timeout: 30000 }); await sleep(500);
console.log('full-prompt test ->', (await txt('h1')).slice(0, 40));
await go('#/import'); await p.select('#i-sample', 'guardrail_hold'); await p.waitForSelector('#i-info [data-out]', { timeout: 8000 });
console.log('inspect ->', (await txt('#i-info')).slice(0, 100), '| goal:', await p.$eval('#i-goal', e => e.value));
await p.$eval('#i-mde', e => e.value = 7); await click('#i-go'); await p.waitForFunction(() => location.hash.startsWith('#/report/'), { timeout: 15000 }); await sleep(500);
console.log('import decision ->', await p.$$eval('.report h2', e => e.map(x => x.innerText).slice(0, 2).join(' | ')), '|', (await txt('.report .pill')));
await go('#/live'); console.log('groups ->', await p.$$eval('#live-pick optgroup', e => e.map(x => x.label + ':' + x.children.length).join(', ')));
await p.goto(base + 'tools.html#try'); await sleep(900); console.log('tools page ->', await txt('.s-h1'));
console.log('errors:', errs.length ? [...new Set(errs)] : 'none'); await b.close();
