"""The history database: every test, its locked setup, its day-by-day results, its decision record and every click a person made.

One SQLite file: data/history.db (or the path in the CANARY_DB environment variable). It uses Python's own sqlite3, so there is nothing to
install and no database server to run. The local server (python -m canary serve) writes to it and the console reads it when it opens, so a
test launched in one browser shows in every browser on that server and survives a restart. The hosted copy (GitHub Pages) has no server:
it keeps its state in the browser, as before.

Tables
  experiments          one row per test: status and outcome as the console shows them, the engine's verdict once its day is reached,
                       the prompts' hashes, and `doc` = the exact object the console renders (so a reload shows the same screen)
  experiment_versions  the locked setup (config JSON and its hash)                     } same columns as the export (canary/export_db.py),
  daily_results        per day and prompt: leads, conversions, rate, every metric     } so one SQL works on both files
  decision_log         the hash-chained decision record: the engine's entries, plus the approval / rejection / rollback entries once a
                       person clicks. A record whose chain does not verify is refused.
  prompt_texts         prompt texts by hash: a 170 KB prompt is stored once however many tests use it
  test_state           where each test is in the console: day played, paused, approval, rollback, stop, holdback days, learning note
  actions              append-only: every click that changed a test (advance a day, approve, reject, roll back, pause, stop, reset ...)
  app_state            drafts, saved settings (custom metrics) and the Prompt Library's own log
  meta                 schema version and the reset epoch

The demo tests and the History samples are generated by code (canary/console.py); they are written here too (origin 'demo' / 'sample') so
the database holds every test the History screen shows. Launched tests (origin 'launched' / 'files') are locked: their record never changes.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import re
import secrets
import sqlite3
import tempfile
import threading
from datetime import datetime, timezone
from pathlib import Path

from . import catalog
from .export_db import _daily_rows, _event_row, _j
from .ledger import verify

ROOT = Path(__file__).resolve().parent.parent
DB = Path(os.environ.get("CANARY_DB") or ROOT / "data" / "history.db")
SCHEMA_VERSION = 2                     # 2: test_state.rev and app_state.rev (a stale browser cannot overwrite a newer save)
BIG_TEXT = 20000                       # strings longer than this (prompt texts) are stored once in prompt_texts
APP_KEYS = ("drafts", "settings", "libLog", "libRolled")
ID_RE = re.compile(r"[A-Za-z0-9_.:-]{1,120}")
_wlock = threading.Lock()              # one writer at a time (SQLite allows one; this keeps the server's threads polite)

SCHEMA = """
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- One row per test. status: Scheduled / Running / Awaiting approval / Completed / Stopped (as the console shows it now).
-- outcome = the console's words after people acted (Promoted, Rejected: kept A, Promoted, then rolled back ...); NULL while running.
-- decision = the engine's verdict once its day is reached. doc = the object the console renders (prompt texts as {"$text": hash}).
CREATE TABLE IF NOT EXISTS experiments (
  id              TEXT PRIMARY KEY,
  origin          TEXT NOT NULL CHECK (origin IN ('demo', 'sample', 'launched', 'files')),
  name            TEXT NOT NULL,
  hypothesis      TEXT,
  status          TEXT NOT NULL CHECK (status IN ('Scheduled', 'Running', 'Awaiting approval', 'Completed', 'Stopped')),
  outcome         TEXT,
  decision        TEXT,
  decision_reason TEXT,
  segment_rule    TEXT,
  primary_goal    TEXT,
  share_b         REAL,
  window_days     INTEGER,
  rule_set        TEXT,
  variant_a_hash  TEXT,
  variant_b_hash  TEXT,
  config_hash     TEXT NOT NULL,
  ledger_head     TEXT NOT NULL,
  created_at      TEXT NOT NULL,                       -- when this database first stored the test (server clock, UTC)
  updated_at      TEXT NOT NULL,
  doc             TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_exp_status ON experiments (status);

CREATE TABLE IF NOT EXISTS experiment_versions (
  experiment_id TEXT NOT NULL REFERENCES experiments (id) ON DELETE CASCADE,
  version       INTEGER NOT NULL,
  config        TEXT NOT NULL,
  config_hash   TEXT NOT NULL,
  locked_at     TEXT,
  PRIMARY KEY (experiment_id, version)
);

-- CUMULATIVE up to the last look of each day; one row per day and prompt (A / B).
CREATE TABLE IF NOT EXISTS daily_results (
  experiment_id TEXT NOT NULL REFERENCES experiments (id) ON DELETE CASCADE,
  day           INTEGER NOT NULL,
  variant       TEXT NOT NULL CHECK (variant IN ('A', 'B')),
  leads         INTEGER NOT NULL,
  conversions   INTEGER NOT NULL,
  rate          REAL,
  metric_values TEXT,
  test_results  TEXT,
  PRIMARY KEY (experiment_id, day, variant)
);

-- entry_hash = sha256(prev_hash + body); the first prev_hash is 64 zeros. body = the exact JSON text that was hashed.
CREATE TABLE IF NOT EXISTS decision_log (
  experiment_id TEXT NOT NULL REFERENCES experiments (id) ON DELETE CASCADE,
  time          TEXT,
  event         TEXT NOT NULL,
  reason        TEXT,
  evidence      TEXT,
  version       INTEGER,
  entry_hash    TEXT NOT NULL,
  prev_hash     TEXT NOT NULL,
  seq           INTEGER NOT NULL,
  type          TEXT NOT NULL,
  body          TEXT NOT NULL,
  PRIMARY KEY (experiment_id, seq)
);

CREATE TABLE IF NOT EXISTS prompt_texts (
  hash       TEXT PRIMARY KEY,                         -- first 16 hex characters of sha256(text)
  text       TEXT NOT NULL,
  first_seen TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS test_state (
  experiment_id TEXT PRIMARY KEY REFERENCES experiments (id) ON DELETE CASCADE,
  day           INTEGER,
  paused        INTEGER,
  approval      TEXT,
  rolled_back   INTEGER,
  manual_stop   INTEGER,
  started       INTEGER,
  holdback_days INTEGER,
  learning      TEXT,
  state         TEXT NOT NULL,                         -- the console's whole state for the test, JSON
  updated_at    TEXT NOT NULL,
  rev           INTEGER NOT NULL DEFAULT 0             -- +1 on every change; a save based on an older rev is refused
);

-- Append-only. Kept when a test is deleted by a reset, so the trail of clicks always survives.
CREATE TABLE IF NOT EXISTS actions (
  id            INTEGER PRIMARY KEY,
  at            TEXT NOT NULL,                         -- server time (UTC) the click was saved
  experiment_id TEXT,
  test_name     TEXT,
  action        TEXT NOT NULL,
  detail        TEXT
);
CREATE INDEX IF NOT EXISTS idx_actions_exp ON actions (experiment_id, id);

CREATE TABLE IF NOT EXISTS app_state (
  key        TEXT PRIMARY KEY CHECK (key IN ('drafts', 'settings', 'libLog', 'libRolled')),
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  rev        INTEGER NOT NULL DEFAULT 0
);
"""

# The console's words for a test's state (web/console/00-core.js KIND_LABEL)
LABEL = {"PROMOTE": "Promoted", "STOP_HARM": "Stopped: B worse", "LOSS": "Keep A: B was worse (a loss)", "STOP_GUARDRAIL": "Stopped: guardrail",
         "HOLD_FOR_APPROVAL": "Held for approval", "INCONCLUSIVE": "Inconclusive, keep A", "HALT_SRM": "Halted: broken test",
         "STOPPED_MANUAL": "Stopped by a person", "REJECTED": "Rejected: kept A", "ROLLED_BACK": "Promoted, then rolled back"}
STOPPED = {"STOP_HARM", "STOP_GUARDRAIL", "HALT_SRM", "STOPPED_MANUAL"}


class StoreError(ValueError):
    pass


class EpochMismatch(StoreError):
    """The history was reset after this browser last read it: the browser must reload instead of writing its old state back."""


class Conflict(StoreError):
    """Another browser saved a newer version of the same item: this browser must reload instead of overwriting it."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def connect(db: Path | str | None = None) -> sqlite3.Connection:
    path = Path(db or DB)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(str(path), timeout=15)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA foreign_keys = ON")
    con.execute("PRAGMA journal_mode = WAL")          # readers never wait for the writer
    con.execute("PRAGMA busy_timeout = 15000")
    return con


_ready: set = set()


def init(db=None) -> None:
    """Create the tables (once per file and process) and bring an older file up to this schema."""
    path = Path(db or DB)
    if str(path) in _ready and path.exists():
        return
    con = connect(path)
    try:
        with _wlock, con:
            con.executescript(SCHEMA)
            for table in ("test_state", "app_state"):                 # schema 1 -> 2
                if "rev" not in [r[1] for r in con.execute(f"PRAGMA table_info({table})")]:
                    con.execute(f"ALTER TABLE {table} ADD COLUMN rev INTEGER NOT NULL DEFAULT 0")
            con.execute("INSERT OR IGNORE INTO meta VALUES ('epoch', ?)", (secrets.token_hex(6),))
            con.execute("INSERT OR IGNORE INTO meta VALUES ('created_at', ?)", (_now(),))
            con.execute("INSERT INTO meta VALUES ('schema_version', ?) ON CONFLICT (key) DO UPDATE SET value = excluded.value", (str(SCHEMA_VERSION),))
    finally:
        con.close()
    _ready.add(str(path))


def epoch(con) -> str:
    return con.execute("SELECT value FROM meta WHERE key = 'epoch'").fetchone()[0]


# ---------------------------------------------------------------------------- prompt texts stored once

def _pack(o, con, now):
    """Long strings (prompt texts) -> {"$text": hash}, the text written once to prompt_texts."""
    if isinstance(o, dict):
        return {k: _pack(v, con, now) for k, v in o.items()}
    if isinstance(o, list):
        return [_pack(v, con, now) for v in o]
    if isinstance(o, str) and len(o) > BIG_TEXT:
        h = hashlib.sha256(o.encode()).hexdigest()[:16]
        con.execute("INSERT OR IGNORE INTO prompt_texts VALUES (?, ?, ?)", (h, o, now))
        return {"$text": h}
    return o


def _unpack(o, texts):
    if isinstance(o, dict):
        if len(o) == 1 and "$text" in o:
            return texts.get(o["$text"], "")
        return {k: _unpack(v, texts) for k, v in o.items()}
    if isinstance(o, list):
        return [_unpack(v, texts) for v in o]
    return o


# ---------------------------------------------------------------------------- state and status (mirrors view() in web/console/00-core.js)

def default_state(doc: dict, origin: str) -> dict:
    """The state the console gives a test it has not touched yet (dyn() in 00-core.js)."""
    rec = doc["record"]
    past = origin == "sample"
    day = doc["start_day"] if doc.get("kind") == "simulated" and doc.get("start_day") else 9999 if past or origin == "files" else 1
    return {"day": day, "paused": False, "approval": "rejected" if past and rec["result"]["kind"] == "HOLD_FOR_APPROVAL" else None,
            "rolledBack": False, "manualStop": False, "learning": ""}


def view(doc: dict, st: dict) -> dict:
    """Status, outcome and visible decision of a test at its current day, the same way the console works them out."""
    rec, res = doc["record"], doc["record"]["result"]
    ld = max((r["day"] for r in rec.get("looks") or []), default=0)
    day = min(int(st.get("day") or 1), max(ld, 1))
    sched = bool(doc.get("scheduled")) and not st.get("started")
    decided = res.get("status") != "running" and day >= ld and not sched
    kind = res["kind"] if decided else "CONTINUE"
    if kind == "STOP_HARM" and res.get("cause") == "loss_at_end":
        kind = "LOSS"
    if st.get("manualStop") and not decided:
        kind = "STOPPED_MANUAL"
    if decided and kind == "HOLD_FOR_APPROVAL" and st.get("approval") in ("approved", "rejected"):
        kind = "PROMOTE" if st["approval"] == "approved" else "REJECTED"
    if kind == "PROMOTE" and st.get("rolledBack"):
        kind = "ROLLED_BACK"
    if sched:
        status = "Scheduled"
    elif kind in STOPPED:
        status = "Stopped"
    elif kind == "HOLD_FOR_APPROVAL":
        status = "Awaiting approval"
    elif decided:
        status = "Completed"
    else:
        status = "Running"
    return {"status": status, "outcome": LABEL.get(kind) if kind != "CONTINUE" else None, "decided": decided, "day": day, "last_day": ld}


def _tail(rec: dict, st: dict) -> list:
    """The decision-record entries a person's click adds (pre-chained by the engine: canary/engine.decision_tails)."""
    tails = rec.get("tails") or {}
    key = ("approve" if st.get("approval") == "approved" else ("auto_reject" if st.get("auto") else "reject") if st.get("approval") == "rejected"
           else ("auto_rollback" if st.get("autoRoll") else "rollback") if st.get("rolledBack") else None)
    return list(tails.get(key) or []) if key else []


def actions_between(old: dict, new: dict) -> list[tuple[str, dict]]:
    """The clicks that turn one state into the next."""
    out = []
    od, nd = int(old.get("day") or 0), int(new.get("day") or 0)
    if nd != od:
        out.append(("advance_day" if nd > od else "set_day", {"from": od, "to": nd}))
    oh, nh = int(old.get("hold") or 0), int(new.get("hold") or 0)
    if nh != oh:
        out.append(("holdback_day", {"from": oh, "to": nh}))
    if new.get("approval") != old.get("approval"):
        act = {"approved": "approve", "rejected": "reject"}.get(new.get("approval"), "approval_cleared")
        out.append(("autopilot_" + act if new.get("auto") and act == "reject" else act, {"by": "autopilot"} if new.get("auto") and act == "reject" else {}))
    for key, on, off in (("rolledBack", "rollback", "rollback_undone"), ("manualStop", "stop", "stop_undone"), ("paused", "pause", "resume"),
                         ("started", "start", "unstart")):
        if bool(new.get(key)) != bool(old.get(key)):
            auto = key == "rolledBack" and new.get(key) and new.get("autoRoll")
            out.append(("autopilot_" + on if auto else on if new.get(key) else off, {"by": "autopilot"} if auto else {}))
    if (new.get("learning") or "") != (old.get("learning") or ""):
        out.append(("learning_note", {"text": str(new.get("learning") or "")[:500]}))
    return out


# ---------------------------------------------------------------------------- writing one test

def _check_doc(doc) -> None:
    if not isinstance(doc, dict) or not isinstance(doc.get("id"), str) or not ID_RE.fullmatch(doc["id"]):
        raise StoreError("a test needs an id of 1-120 letters, digits, '_', '.', ':' or '-'")
    rec = doc.get("record")
    if not isinstance(rec, dict) or not all(k in rec for k in ("config", "config_hash", "looks", "result", "ledger", "ledger_head")):
        raise StoreError(f"{doc['id']}: the test has no complete engine record")
    ok, bad = verify(rec["ledger"])
    if not ok or not rec["ledger"] or rec["ledger"][-1]["hash"] != rec["ledger_head"]:
        raise StoreError(f"{doc['id']}: its decision record does not verify (entry {bad}); it was changed after the engine wrote it")


def _write_log(con, exp_id: str, version: int, rec: dict, st: dict) -> None:
    con.execute("DELETE FROM decision_log WHERE experiment_id = ?", (exp_id,))
    entries = list(rec["ledger"]) + _tail(rec, st)
    if not verify(entries)[0]:
        raise StoreError(f"{exp_id}: the person's entries do not chain onto the decision record")
    con.executemany("INSERT INTO decision_log VALUES (?,?,?,?,?,?,?,?,?,?,?)", [_event_row(exp_id, version, x) for x in entries])


def _refresh(con, exp_id: str, doc: dict, st: dict, now: str) -> None:
    """Re-derive the row's status / outcome / decision and the decision log from the state."""
    v, res = view(doc, st), doc["record"]["result"]
    con.execute("UPDATE experiments SET status = ?, outcome = ?, decision = ?, decision_reason = ?, updated_at = ? WHERE id = ?",
                (v["status"], v["outcome"], res["kind"] if v["decided"] else None, res.get("reason") if v["decided"] else None, now, exp_id))
    _write_log(con, exp_id, doc["record"]["config"].get("version", 1), doc["record"], st)


def _segment_rule(cfg: dict) -> str:
    try:
        return catalog.describe(catalog.validate_segment(cfg.get("segment")))
    except Exception:
        return str(cfg.get("segment") or "")


def _insert_test(con, doc: dict, origin: str, now: str) -> None:
    rec, cfg = doc["record"], doc["record"]["config"]
    version = cfg.get("version", 1)
    packed = _pack(doc, con, now)
    st = default_state(doc, origin)
    v = view(doc, st)
    con.execute("INSERT INTO experiments VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (doc["id"], origin, cfg.get("name") or doc["id"], doc.get("hypothesis"), v["status"], v["outcome"], None, None, _segment_rule(cfg),
                 cfg.get("primary_goal"), cfg.get("share_b"), cfg.get("window_days"), cfg.get("rule_set"),
                 rec["variants"]["A"]["hash"], rec["variants"]["B"]["hash"], rec["config_hash"], rec["ledger_head"], now, now,
                 json.dumps(packed, separators=(",", ":"))))
    created = json.loads(rec["ledger"][0]["body"])
    con.execute("INSERT INTO experiment_versions VALUES (?,?,?,?,?)", (doc["id"], version, _j(cfg), rec["config_hash"], created.get("ts")))
    con.executemany("INSERT INTO daily_results VALUES (?,?,?,?,?,?,?,?)", _daily_rows(doc["id"], rec))
    _refresh(con, doc["id"], doc, st, now)


TEXT_REF = re.compile(r'"\$text":"([0-9a-f]{16})"')


def _texts(con, *blobs: str) -> dict:
    """The prompt texts a stored JSON text refers to."""
    hashes = sorted({h for b in blobs for h in TEXT_REF.findall(b)})
    if not hashes:
        return {}
    return {r["hash"]: r["text"] for r in con.execute(f"SELECT hash, text FROM prompt_texts WHERE hash IN ({','.join('?' * len(hashes))})", hashes)}


def _doc_of(con, exp_id: str):
    row = con.execute("SELECT origin, doc, ledger_head FROM experiments WHERE id = ?", (exp_id,)).fetchone()
    if not row:
        return None
    return {"origin": row["origin"], "doc": _unpack(json.loads(row["doc"]), _texts(con, row["doc"])), "ledger_head": row["ledger_head"]}


def _state_of(con, exp_id: str):
    row = con.execute("SELECT state FROM test_state WHERE experiment_id = ?", (exp_id,)).fetchone()
    return json.loads(row["state"]) if row else None


def _log_action(con, now: str, exp_id, name, action: str, detail: dict | None = None) -> None:
    con.execute("INSERT INTO actions (at, experiment_id, test_name, action, detail) VALUES (?,?,?,?,?)",
                (now, exp_id, name, action, json.dumps(detail or {}, separators=(",", ":"))))


# ---------------------------------------------------------------------------- the public calls

def seed(bundle: dict, db=None) -> dict:
    """Write the demo tests and the History samples from the console bundle. Re-running is cheap: a test whose record is unchanged is skipped;
    one whose record changed (the code was rebuilt) is replaced, keeping its state and its clicks."""
    init(db)
    con = connect(db)
    added = replaced = 0
    try:
        with _wlock, con:
            con.execute("BEGIN IMMEDIATE")                         # the write lock from the first read: no other process slips in
            now = _now()
            for origin, docs in (("demo", bundle.get("demo") or []), ("sample", bundle.get("past") or [])):
                for doc in docs:
                    _check_doc(doc)
                    row = con.execute("SELECT origin, ledger_head FROM experiments WHERE id = ?", (doc["id"],)).fetchone()
                    if row and row["ledger_head"] == doc["record"]["ledger_head"]:
                        continue
                    st = _state_of(con, doc["id"])
                    old_rev = (con.execute("SELECT rev FROM test_state WHERE experiment_id = ?", (doc["id"],)).fetchone() or [0])[0]
                    if row:
                        con.execute("DELETE FROM test_state WHERE experiment_id = ?", (doc["id"],))
                        con.execute("DELETE FROM experiments WHERE id = ?", (doc["id"],))
                        replaced += 1
                    else:
                        added += 1
                    _insert_test(con, doc, origin, now)
                    if st is not None:
                        _put_state(con, doc["id"], doc, st, now, log=False)
                        con.execute("UPDATE test_state SET rev = ? WHERE experiment_id = ?", (old_rev + 1, doc["id"]))   # a tab holding an old rev stays stale
            # an untouched demo test needs no row (older versions wrote one): without it, a browser from before the database keeps its own progress
            # (only rows nobody ever clicked: a state a person set back to the default is a real save and stays, so an older tab cannot undo it)
            for r in con.execute("SELECT t.experiment_id, t.state, e.origin FROM test_state t JOIN experiments e ON e.id = t.experiment_id "
                                 "WHERE e.origin IN ('demo', 'sample') AND NOT EXISTS (SELECT 1 FROM actions a WHERE a.experiment_id = t.experiment_id)").fetchall():
                d = _doc_of(con, r["experiment_id"])
                if _canon(json.loads(r["state"])) == _canon(default_state(d["doc"], r["origin"])):
                    con.execute("DELETE FROM test_state WHERE experiment_id = ?", (r["experiment_id"],))
    finally:
        con.close()
    return {"added": added, "replaced": replaced}


def _put_state(con, exp_id: str, doc: dict, st: dict, now: str, log: bool = True) -> int:
    row = con.execute("SELECT origin, name FROM experiments WHERE id = ?", (exp_id,)).fetchone()
    old = _state_of(con, exp_id)
    if old is None and row["origin"] in ("launched", "files"):
        old = st                                  # a launched test's first state is its launch state: the 'launch' action already says so
    elif old is None:
        old = default_state(doc, row["origin"])
    acts = actions_between(old, st) if log else []
    con.execute("INSERT INTO test_state VALUES (?,?,?,?,?,?,?,?,?,?,?,1) ON CONFLICT (experiment_id) DO UPDATE SET day = excluded.day, "
                "paused = excluded.paused, approval = excluded.approval, rolled_back = excluded.rolled_back, manual_stop = excluded.manual_stop, "
                "started = excluded.started, holdback_days = excluded.holdback_days, learning = excluded.learning, state = excluded.state, "
                "updated_at = excluded.updated_at, rev = test_state.rev + 1",
                (exp_id, st.get("day"), int(bool(st.get("paused"))), st.get("approval"), int(bool(st.get("rolledBack"))), int(bool(st.get("manualStop"))),
                 None if "started" not in st else int(bool(st["started"])), int(st.get("hold") or 0), st.get("learning") or "",
                 json.dumps(st, separators=(",", ":")), now))
    for action, detail in acts:
        _log_action(con, now, exp_id, row["name"], action, detail)
    _refresh(con, exp_id, doc, st, now)
    return len(acts)


def _sane(o):
    """What a browser's JSON can carry but SQLite and JSON.parse cannot: NaN / Infinity become null, a lone surrogate becomes U+FFFD."""
    if isinstance(o, dict):
        return {_sane(k): _sane(v) for k, v in o.items()}
    if isinstance(o, list):
        return [_sane(v) for v in o]
    if isinstance(o, float) and not math.isfinite(o):
        return None
    if isinstance(o, str):
        try:
            o.encode("utf-8")
        except UnicodeEncodeError:
            return o.encode("utf-16", "surrogatepass").decode("utf-16", "replace")
    return o


def _canon(o) -> str:
    return json.dumps(o, sort_keys=True, separators=(",", ":"))


def apply(body: dict, db=None) -> dict:
    """One save from the console, in one transaction:
    {"epoch", "tests": [test objects], "state": {id: state}, "app": {key: value}, "revs": {"s:<id>" | "a:<key>": rev the browser last saw}}.

    A test that is not a valid engine record is not stored and is listed in `rejected` (the rest of the save goes on). A state or app value
    based on an older rev than the stored one is a conflict (another browser saved first): nothing is written and Conflict is raised.
    Sending exactly what is stored is never a conflict. The reply carries the new revs."""
    if not isinstance(body, dict):
        raise StoreError("expected a JSON object")
    body = _sane(body)
    tests, state, app, revs = body.get("tests") or [], body.get("state") or {}, body.get("app") or {}, body.get("revs") or {}
    if not isinstance(tests, list) or not isinstance(state, dict) or not isinstance(app, dict) or not isinstance(revs, dict):
        raise StoreError("tests must be a list; state, app and revs must be objects")
    bad = [k for k in app if k not in APP_KEYS] + [k for k, v in state.items() if not isinstance(v, dict)]
    if bad:
        raise StoreError(f"unknown app keys or states that are not objects: {bad}")
    out = {"tests_added": 0, "states": 0, "actions": 0, "skipped": [], "rejected": [], "revs": {}}
    good = []
    for doc in tests:
        try:
            _check_doc(doc)
            good.append(doc)
        except StoreError as e:
            out["rejected"].append({"id": doc.get("id") if isinstance(doc, dict) else None, "error": str(e)})
    init(db)
    con = connect(db)
    try:
        with _wlock, con:
            con.execute("BEGIN IMMEDIATE")
            cur = epoch(con)
            if body.get("epoch") and body["epoch"] != cur:
                raise EpochMismatch("the history was reset from another browser: reload the page")
            now = _now()
            # 1. conflicts first, so a refused save writes nothing
            stale = []
            for kind, items, table, col in (("s", state, "test_state", "experiment_id"), ("a", app, "app_state", "key")):
                for k, v in items.items():
                    row = con.execute(f"SELECT {'state' if kind == 's' else 'value'} AS v, rev FROM {table} WHERE {col} = ?", (k,)).fetchone()
                    if row is None:
                        continue
                    stored = json.loads(row["v"]) if kind == "s" else _unpack(json.loads(row["v"]), _texts(con, row["v"]))
                    if _canon(stored) != _canon(v) and int(revs.get(f"{kind}:{k}") or 0) != row["rev"]:
                        stale.append(f"{kind}:{k}")
            if stale:
                raise Conflict(f"another browser saved a newer version of {', '.join(stale[:5])}: reload the page")
            # 2. new tests (a launched test is locked: same id, other record -> rejected)
            for doc in good:
                row = con.execute("SELECT origin, ledger_head FROM experiments WHERE id = ?", (doc["id"],)).fetchone()
                if row:
                    if row["origin"] in ("demo", "sample"):
                        out["rejected"].append({"id": doc["id"], "error": f"{doc['id']} is a demo or sample test; it is written by the server only"})
                    elif row["ledger_head"] != doc["record"]["ledger_head"]:
                        out["rejected"].append({"id": doc["id"], "error": f"{doc['id']} is locked: its decision record cannot change after launch"})
                    continue                                          # already stored, unchanged
                origin = "files" if doc.get("kind") == "files" else "launched"
                _insert_test(con, doc, origin, now)
                _log_action(con, now, doc["id"], doc["record"]["config"].get("name"), "import_results" if origin == "files" else "launch",
                            {"config_hash": doc["record"]["config_hash"], "scheduled": bool(doc.get("scheduled"))})
                out["tests_added"] += 1
            # 3. states (a state identical to the stored one is not written again)
            for exp_id, st in state.items():
                d = _doc_of(con, exp_id)
                if d is None:
                    out["skipped"].append(exp_id)                    # e.g. an offline replay, or a test that was rejected above
                    continue
                old = con.execute("SELECT state FROM test_state WHERE experiment_id = ?", (exp_id,)).fetchone()
                untouched = old is None and d["origin"] in ("demo", "sample") and _canon(st) == _canon(default_state(d["doc"], d["origin"]))
                if untouched:
                    out["revs"][f"s:{exp_id}"] = 0                # nothing to keep: the console's own default for a test nobody touched
                    continue
                if old is None or _canon(json.loads(old["state"])) != _canon(st):
                    out["actions"] += _put_state(con, exp_id, d["doc"], st, now)
                    out["states"] += 1
                out["revs"][f"s:{exp_id}"] = con.execute("SELECT rev FROM test_state WHERE experiment_id = ?", (exp_id,)).fetchone()[0]
            # 4. drafts, settings, the Prompt Library's log
            for k, v in app.items():
                old = con.execute("SELECT value FROM app_state WHERE key = ?", (k,)).fetchone()
                text = json.dumps(_pack(v, con, now), separators=(",", ":"))
                if not (old and old["value"] == text):
                    con.execute("INSERT INTO app_state VALUES (?,?,?,1) ON CONFLICT (key) DO UPDATE SET value = excluded.value, "
                                "updated_at = excluded.updated_at, rev = app_state.rev + 1", (k, text, now))
                    if k == "drafts":
                        _log_action(con, now, None, None, "drafts_saved", {"count": len(v) if isinstance(v, list) else None})
                    elif k == "settings":
                        _log_action(con, now, None, None, "settings_saved", {})
                out["revs"][f"a:{k}"] = con.execute("SELECT rev FROM app_state WHERE key = ?", (k,)).fetchone()[0]
    finally:
        con.close()
    out["epoch"] = cur
    return out


def load(db=None) -> dict:
    """What the console needs on start: launched tests (newest first), every stored state, the app keys and the epoch."""
    init(db)
    con = connect(db)
    try:
        con.execute("BEGIN")                                       # one snapshot: the states and their revs are read at the same moment
        ids = [r["id"] for r in con.execute("SELECT id FROM experiments WHERE origin IN ('launched', 'files') ORDER BY created_at DESC, rowid DESC")]
        launched = [_doc_of(con, i)["doc"] for i in ids]
        dyn = {r["experiment_id"]: json.loads(r["state"]) for r in con.execute("SELECT experiment_id, state FROM test_state")}
        app = {r["key"]: _unpack(json.loads(r["value"]), _texts(con, r["value"])) for r in con.execute("SELECT key, value FROM app_state").fetchall()}
        revs = {f"s:{r[0]}": r[1] for r in con.execute("SELECT experiment_id, rev FROM test_state")}
        revs.update({f"a:{r[0]}": r[1] for r in con.execute("SELECT key, rev FROM app_state")})
        out = {"epoch": epoch(con), "launched": launched, "dyn": dyn, "app": app, "revs": revs, "info": _info(con)}
        con.rollback()
        return out
    finally:
        con.close()


def reset(db=None) -> dict:
    """Clear launched tests, every state, drafts and settings; keep the demo tests, the samples and the click log (with a 'reset' entry)."""
    init(db)
    con = connect(db)
    try:
        with _wlock, con:
            con.execute("BEGIN IMMEDIATE")
            n = con.execute("SELECT COUNT(*) FROM experiments WHERE origin IN ('launched', 'files')").fetchone()[0]
            con.execute("DELETE FROM experiments WHERE origin IN ('launched', 'files')")
            con.execute("DELETE FROM test_state")
            con.execute("DELETE FROM app_state")
            now = _now()
            for r in con.execute("SELECT id, doc FROM experiments").fetchall():         # back to the untouched demo
                d = _doc_of(con, r["id"])
                _refresh(con, r["id"], d["doc"], default_state(d["doc"], d["origin"]), now)
            used = {h for r in con.execute("SELECT doc FROM experiments") for h in TEXT_REF.findall(r["doc"])}
            con.executemany("DELETE FROM prompt_texts WHERE hash = ?", [(h,) for (h,) in con.execute("SELECT hash FROM prompt_texts").fetchall() if h not in used])
            new = secrets.token_hex(6)
            con.execute("UPDATE meta SET value = ? WHERE key = 'epoch'", (new,))
            _log_action(con, now, None, None, "reset", {"launched_tests_removed": n})
    finally:
        con.close()
    return {"epoch": new, "removed": n}


def _info(con) -> dict:
    q = lambda s: con.execute(s).fetchone()[0]
    by = {r["origin"]: r["n"] for r in con.execute("SELECT origin, COUNT(*) AS n FROM experiments GROUP BY origin")}
    return {"path": con.execute("PRAGMA database_list").fetchone()[2], "tests": by, "actions": q("SELECT COUNT(*) FROM actions"),
            "decision_entries": q("SELECT COUNT(*) FROM decision_log"), "engine": f"SQLite {sqlite3.sqlite_version}"}


def info(db=None) -> dict:
    init(db)
    con = connect(db)
    try:
        out = _info(con)
    finally:
        con.close()
    p = Path(out["path"])
    out["size_bytes"] = p.stat().st_size if p.exists() else 0
    return out


def snapshot(db=None) -> bytes:
    """A consistent copy of the whole database file (safe while the server writes), for the Download button."""
    init(db)
    src = connect(db)
    fd, tmp = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    try:
        dst = sqlite3.connect(tmp)
        with dst:
            src.backup(dst)
        dst.execute("PRAGMA journal_mode = DELETE")
        dst.close()
        return Path(tmp).read_bytes()
    finally:
        src.close()
        Path(tmp).unlink(missing_ok=True)


def summary(db=None, limit: int = 15) -> str:
    """Plain text for `python -m canary history`: every test and the latest clicks."""
    init(db)
    con = connect(db)
    try:
        rows = con.execute("SELECT name, origin, status, outcome, created_at FROM experiments ORDER BY origin = 'sample', created_at DESC, name").fetchall()
        acts = con.execute("SELECT at, test_name, action, detail FROM actions ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
        lines = [f"History database: {_info(con)['path']}", "", f"{'Test':<44}{'Origin':<10}{'Status':<19}Outcome"]
        lines += [f"{r['name'][:43]:<44}{r['origin']:<10}{r['status']:<19}{r['outcome'] or '-'}" for r in rows]
        lines += ["", f"Latest {len(acts)} clicks:"] + [f"  {a['at']}  {a['action']:<15}{a['test_name'] or '-'}  {a['detail'] if a['detail'] != '{}' else ''}" for a in acts]
        return "\n".join(lines)
    finally:
        con.close()
