/* The one-page final report of a test (print view), and Clone. The list of tests is All experiments (35-experiments.js). */

/** Prompt A and prompt B of a test in full, where they are known (a results file carries no prompts). */
function promptsOf(e) {
  if (e.kind === "files") return null;
  const c = e.record.config, base = C.library.base_text || "";
  const a = e.prompt_a && e.prompt_a.hash && e.prompt_a.hash !== C.library.base.hash ? versionText(productionState().versions.find(x => x.hash === e.prompt_a.hash)) : base;
  let b = e.prompt_b || null;
  if (!b && (C.library.edits || {})[c.variant_b]) { try { b = applyEdits(base, C.library.edits[c.variant_b]); } catch (err) { b = null; } }
  return b ? { a, b, aId: (e.prompt_a && e.prompt_a.id) || "v1" } : null;
}
function cloneOf(e) {
  const c = e.record.config, seg = segList(segOf(e)), pr = promptsOf(e), ms = c.metrics || [];
  const prim = ms.find(x => x.role === "primary"), keep = d => d && !metricByKey(d.key) ? [d] : [];
  startWizard({ name: c.name + " (re-run)", change: e.hypothesis || "", promptB: pr ? pr.b : null, segRows: seg.map(r => ({ column: r.column, values: r.values.slice() })), audienceSet: true,
    primary: prim ? prim.def.key : (C.metrics.some(m => m.key === c.primary_goal) ? c.primary_goal : null),
    guards: ms.length ? ms.filter(x => x.role === "guardrail").map(x => ({ key: x.def.key, direction: x.def.direction, limit: { ...x.limit } })) : (c.secondary_role === "guardrail" ? [{ key: "duration_s", direction: "lower", limit: { value: Math.round(c.guardrail_margin * 100), kind: "rel" } }] : []).concat(c.guard_rate === "early_hangup" ? [{ key: "early_hangup", direction: "lower", limit: { value: Math.round(c.guard_rate_margin * 100), kind: "pts" } }] : []),
    secondary: ms.filter(x => x.role === "secondary").map(x => ({ key: x.def.key, direction: x.def.direction })), localMetrics: ms.flatMap(x => keep(x.def)),
    share: Math.min(0.5, c.share_b), shareTouched: true, lenMode: [7, 14, 21, 28].includes(c.window_days) ? "custom" : "rec", customDays: [7, 14, 21, 28].includes(c.window_days) ? c.window_days : null, rule: c.rule_set, confidence: 1 - 2 * c.alpha,
    approval: c.approval, harm: Math.round((1 - c.alpha_harm_daily) * 1000) / 1000, minLeads: c.min_per_arm, assignment: c.assignment || "stratified", step: 1,
    preset: e.truth && e.truth.effect_rel != null ? (e.truth.effect_rel > 0 ? "win" : e.truth.effect_rel < 0 ? "worse" : "flat") : "win" });
}

ROUTES.report = (el, id) => {
  const e = byId(id); if (!e) { el.innerHTML = head("Report", "") + `<div class="empty">That test was not found. <a href="#/experiments">See all experiments</a>.</div>`; return; }
  const v = view(e), c = v.config, rec = e.record, cur = v.cur;
  if (!v.ended || !cur) { el.innerHTML = head(c.name, "The final report is written when the test ends.") + `<div class="empty">This test has not ended yet (${esc(v.status[0])}). <a href="#/experiments/${encodeURIComponent(e.id)}">Open its page</a>.</div>`; return; }
  const ciA = armCI(cur, "A", c), ciB = armCI(cur, "B", c), lr = liftRange(cur, c), gl = guardList(v), goal = goalName(c), sec = secondaryList(v), pr = promptsOf(e), avg = primaryDef(c).type === "average";
  const ents = rec.ledger.concat(tailOf(rec, v.d));
  const sugg = ["slot options work", "longer intro hurts", "small effect: needs more leads", "call length is the catch", "broken tracking: rerun"];
  el.innerHTML = head("Final report", "A frozen, one-page record of this test.", `<a class="btn" href="#/experiments/${encodeURIComponent(e.id)}">← Back to the test</a><button class="btn" id="r-clone">Clone and re-run</button><button class="btn" id="r-csv">Export CSV</button><button class="btn primary" onclick="print()">Print</button>`) +
    `<div class="report card"><div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><h2 style="margin:0;font-size:20px">${esc(c.name)}</h2>${pill(KIND_LABEL[v.kind] || v.kind, KIND_CLASS[v.kind])}</div>
      <p class="note">${fdate(c.start)} · ${v.ld} day${v.ld === 1 ? "" : "s"} · config v${c.version || 1} ${info("Locked config " + rec.config_hash)} · ${esc(e.kind === "files" ? "results supplied as files" : "simulated results")}</p>
      ${e.hypothesis ? `<p>${esc(e.hypothesis)}</p>` : ""}
      <h2>Decision</h2><p class="banner ${{ PROMOTE: "pos", STOP_HARM: "neg", LOSS: "neg", STOP_GUARDRAIL: "neg", HOLD_FOR_APPROVAL: "warn", HALT_SRM: "warn", ROLLED_BACK: "warn", STOPPED_MANUAL: "neg" }[v.kind] || ""}" style="display:block">${esc(v.kind === "STOPPED_MANUAL" ? "A person stopped the test early." : v.res.reason)}${v.d.approval ? (v.d.auto ? ` Nobody answered within ${heldDays()} days, so the autopilot kept A.` : ` A person ${v.d.approval} it.`) : ""}${v.d.rolledBack ? (v.d.autoRoll ? " The holdback week then raised an alert and the autopilot rolled it back." : " It was then rolled back by a person.") : ""}</p>
      <h2>In plain words</h2><p>${esc(plainSummary(e))}</p>
      <h2>The numbers</h2><div class="tbl-wrap"><table><thead><tr><th></th><th class="num">Leads</th>${cur.dA != null ? `<th class="num">${avg ? "Counted" : "In the denominator"}</th>` : ""}${avg ? "" : `<th class="num">Goal reached</th>`}<th class="num">${avg ? "Average" : "Rate"}</th><th class="num">95% range</th></tr></thead><tbody>
        <tr><td><span class="dot a"></span>A: today's prompt</td><td class="num">${nf(cur.nA)}</td>${cur.dA != null ? `<td class="num">${nf(cur.dA)}</td>` : ""}${avg ? "" : `<td class="num">${nf(cur.xA)}</td>`}<td class="num">${fmtP(cur.rateA, c)}</td><td class="num">${fmtP(ciA[0], c)} to ${fmtP(ciA[1], c)}</td></tr>
        <tr><td><span class="dot b"></span>B: new prompt</td><td class="num">${nf(cur.nB)}</td>${cur.dB != null ? `<td class="num">${nf(cur.dB)}</td>` : ""}${avg ? "" : `<td class="num">${nf(cur.xB)}</td>`}<td class="num">${fmtP(cur.rateB, c)}</td><td class="num">${fmtP(ciB[0], c)} to ${fmtP(ciB[1], c)}</td></tr>
        <tr><td><b>Lift of B over A</b></td><td></td>${cur.dA != null ? "<td></td>" : ""}${avg ? "" : "<td></td>"}<td class="num"><b>${fmtD(cur.diff, c)}</b></td><td class="num">${rangeD(lr.lo, lr.hi, c)}${lr.interim ? "<div class=\"note\">interim: the test stopped before its final call</div>" : ""}</td></tr></tbody></table></div>
      <h2>Over time</h2><div class="legend"><span><i style="border-color:var(--a)"></i>A</span><span><i style="border-color:var(--b)"></i>B</span><span><i class="band" style="background:var(--ink-2)"></i>95% range</span></div><div id="trend"></div>
      <h2>Safety checks</h2><div class="checkgrid">${gl.map(x => `<div class="check ${x.st.cls === "pos" ? "ok" : x.st.cls === "neg" ? "bad" : "wait"}" title="${x.g ? esc(x.st.value + " (limit " + x.st.lim + "; " + x.conf + "% range " + x.st.range + ")") : "not enough data"}"><span class="ico">${x.st.cls === "pos" ? "\u2713" : x.st.cls === "neg" ? "\u2715" : "\u2026"}</span><span><b>${esc(x.name)}${x.def ? " (guardrail)" : ""}:</b> ${x.g ? esc(x.st.value) + ", limit " + esc(x.st.lim) : "not enough data"}</span></div>`).join("")}
        <div class="check ${cur.p_srm < 0.001 ? "bad" : "ok"}" title="sample-ratio p = ${cur.p_srm < 0.001 ? cur.p_srm.toExponential(1) : cur.p_srm.toFixed(2)}"><span class="ico">${cur.p_srm < 0.001 ? "\u2715" : "\u2713"}</span><span><b>Split:</b> B received ${pct(cur.nB / cur.n, 1)} of leads (configured ${pct(c.share_b, 0)})</span></div>
        <div class="check ${(rec.result.stickiness || {}).arm_changes ? "bad" : "ok"}"><span class="ico">${(rec.result.stickiness || {}).arm_changes ? "\u2715" : "\u2713"}</span><span><b>Sticky assignment:</b> ${(rec.result.stickiness || {}).checkable === false ? "not checkable from this source" : nf((rec.result.stickiness || {}).arm_changes) + " leads saw both prompts"}</span></div></div>
      ${v.kind === "INCONCLUSIVE" && v.res.more_leads ? `<h2>What would settle it</h2><ul>${v.res.more_leads.options.map(o => `<li>${o.enough_already ? `Already enough data to detect ${esc(liftWords(o))} (${esc(o.label)}): any real lift is smaller than that.` : `${nf(o.more_leads)} more leads (about ${o.more_days} days) to detect ${esc(liftWords(o))} (${esc(o.label)}).${o.impractical ? " Over a year of traffic: not practical." : ""}`}</li>`).join("")}</ul>` : ""}
      ${fold("Metrics", `<div style="display:grid;gap:4px">${metricsSummaryHtml(c)}</div>${sec.length ? `<h3 style="margin-top:12px">Secondary (for insight only, not used for the decision)</h3>${secondaryHtml(v)}` : ""}`, "goal, guardrails, secondary")}
      ${fold("Audience", `<p>${esc(segDescribe(c.segment))}${rec.result.segment_check ? ` · ${pct(rec.result.segment_check.share_of_traffic, 0)} of traffic, about ${c.metrics ? nf(rec.result.segment_check.eligible_per_day * connectShare()) + " connected" : nf(rec.result.segment_check.eligible_per_day)} leads a day · <b>${esc(segMatchLine(rec))}</b>; ${nf(rec.result.segment_check.out_of_segment_leads)} out-of-segment leads kept today's prompt and were not counted` : ""}</p>`, esc(segRules(c.segment).length ? segDescribe(c.segment) : "all leads"))}
      ${fold("Prompt B", pr ? `<p class="note">${esc((e.record.variants.B || {}).name || "")} against ${esc(pr.aId)} · fingerprint <span class="mono">${esc((e.record.variants.B || {}).hash || "")}</span></p>${diffBlock(pr.a, pr.b)}<details style="margin-top:8px"><summary style="cursor:pointer;font-weight:500">Show the full prompt B</summary><textarea readonly class="prompt-box" rows="14" style="margin-top:8px" aria-label="Prompt B (read-only)">${esc(pr.b)}</textarea></details>` : `<p class="note">${e.kind === "files" ? "The prompts are not part of a results file." : "The full text of this prompt B is not in this browser."}</p>`, pr ? "what changed" : "")}
      ${cur.mix ? fold("Achieved lead mix", `<div class="note" style="margin-bottom:8px">A and B should carry the same mix of lead types. Per-group results are for insight only, never for the decision.</div>${balanceHtml(cur)}`, "A against B by lead type") : ""}
      <h2>Learning</h2><div class="field"><label for="r-learn">One line that feeds the next suggestions</label><input type="text" id="r-learn" list="r-sugg" value="${esc(dyn(e).learning || "")}" placeholder="for example: slot options work"><datalist id="r-sugg">${sugg.map(s => `<option value="${esc(s)}">`).join("")}</datalist></div>
      <h2>Record</h2><p class="note">${ents.length} entries, head <span class="mono">${esc(ents[ents.length - 1].hash.slice(0, 16))}</span> <button class="link" id="r-ver">Re-check in this browser</button> <span id="r-vo"></span></p>
      <p class="note">${e.kind === "files" ? "These results were supplied as files; Picky advises and does not control live traffic." : "The outcomes are simulated with a known injected effect: this report shows the engine decides correctly, not that a real prompt is better."}</p></div>`;
  trendChart($("#trend"), dayRows(rec), v.win, { finalDay: c.rule_set === "final_look" ? v.win : null, c });
  $("#r-clone").onclick = () => cloneOf(e);
  $("#r-csv").onclick = () => download(`${e.id}_report.csv`, avg ? toCsv(["day", "leads_A", "counted_A", "leads_B", "counted_B", "mean_A", "mean_B", "lift_" + (metricUnit(primaryDef(c)) || "units")], dayRows(rec).map(({ day, row }) => [day, row.nA, row.dA, row.nB, row.dB, row.rateA.toFixed(3), row.rateB.toFixed(3), row.diff.toFixed(3)]))
    : toCsv(["day", "leads_A", "goal_A", "leads_B", "goal_B", "rate_A", "rate_B", "lift_pp"], dayRows(rec).map(({ day, row }) => [day, row.nA, row.xA, row.nB, row.xB, row.rateA.toFixed(4), row.rateB.toFixed(4), (row.diff * 100).toFixed(2)])));
  $("#r-learn").onchange = ev => { dyn(e).learning = ev.target.value.trim(); saveDyn(); toast("Learning saved."); };
  $("#r-ver").onclick = async () => { try { $("#r-vo").innerHTML = await chainOk(ents) ? `<b style="color:#167a70">✓ intact</b>` : `<b style="color:#b23b3b">✕ broken</b>`; } catch (err) { $("#r-vo").textContent = String(err.message || err); } };
};
