/* Prompt Library, Decision Log, Settings. */

/** A full prompt B: the live prompt A with a candidate's edits applied (falls back to A, with a note, if the edits no longer fit). */
function fullPromptB(key) { const A = liveA().text, spec = (C.library.edits || {})[key]; if (!spec) return A; try { return applyEdits(A, spec); } catch (err) { toast("This suggestion no longer fits the live prompt: " + err.message + " Prompt B starts as a copy of A."); return A; } }

DYN.libRolled = DYN.libRolled || [];
/** Production versions in the order they were promoted in this demo. v1 is the real prompt as received. */
function productionState() {
  const b = C.library.base, vers = [{ id: "v1", name: b.name, hash: b.hash, parent: null, from: "The real VANI buyer-side prompt, as received", time: null, by: "provided", diff: [], status: "previous", scope: null }];
  promotedExperiments().forEach(({ e, v, time }, i) => {
    const B = e.record.variants.B, id = "v" + (i + 2), by = v.res.kind === "PROMOTE" ? "automatically" : "approved by a person", seg = segOf(e);
    const rolled = v.d.rolledBack || DYN.libRolled.includes(id), scope = segRules(seg).length ? segDescribe(seg) : null;
    vers.push({ id, key: e.record.config.variant_b, name: B.name, hash: B.hash, parent: vers[vers.length - 1].id, from: e.record.config.name, expId: e.id, time, by, diff: B.diff || [], status: rolled ? "rolled back" : "previous", expView: v, scope });
  });
  // a promotion tested on one segment changes the prompt for that segment only: the all-traffic pointer moves only for promotions with no segment
  let live = vers[0]; for (const x of vers) if (x.status !== "rolled back" && !x.scope) live = x;
  vers.forEach(x => { if (x.id === live.id) x.status = "live"; else if (x.scope && x.status !== "rolled back") x.status = "live for a segment"; });
  return { versions: vers, live };
}

ROUTES.library = (el, arg) => {
  const P = productionState(), base = P.versions[0], two = P.live.id === base.id ? [base] : [base, P.live];   // only two prompts: A (the original) and B (what is live now)
  const vers = two.slice().reverse(), sel = two.find(x => x.id === arg) || P.live, prev = sel.id === base.id ? null : base, AB = x => x.id === base.id ? "A" : "B";
  const cands = C.library.candidates, selText = versionText(sel);
  const diffHtml = prev ? diffBlock(versionText(prev), selText) : "", diffNote = prev ? "What changed from A (the original) to B (live now), side by side." : "";
  el.innerHTML = head("Prompt Library", "Every prompt version, what is live, and one-click rollback.") +
    `<div class="banner"><div><b>Live now: ${AB(P.live)}</b> · ${esc(P.live.name)} ${info(`Fingerprint ${P.live.hash}. A production pointer says which version callers hear. Before each call the bot asks the router which prompt this lead gets, then loads that version.`)}</div></div>
    <div class="tbl-wrap"><table><thead><tr><th>Version</th><th>Name</th><th>From test</th><th>Promoted</th><th>Status</th><th></th></tr></thead><tbody>${vers.map(x => `<tr class="click" data-ver="${esc(x.id)}"><td title="fingerprint ${esc(x.hash)}"><b>${AB(x)}</b></td><td>${esc(x.name)}</td><td>${x.expId ? `<a href="#/experiments/${encodeURIComponent(x.expId)}">${esc(x.from)}</a>` : esc(x.from)}</td><td>${x.time ? esc(fdt(x.time)) + `<div class="note">${esc(x.by)}</div>` : "-"}</td>
      <td>${pill(x.status === "live" ? "✓ Live" : x.status === "live for a segment" ? "✓ Live for a segment" : x.status === "rolled back" ? "Rolled back" : "Previous", x.status === "live" ? "pos" : x.status === "live for a segment" ? "run" : x.status === "rolled back" ? "warn" : "plain")}${x.scope ? `<div class="note mono">${esc(x.scope)} only</div>` : ""}</td><td>${(x.status === "live" || x.status === "live for a segment") && x.id !== "v1" ? `<button class="btn sm danger" data-roll="${esc(x.id)}">Rollback</button>` : ""}</td></tr>`).join("")}</tbody></table></div>
    <div class="card" style="margin-top:16px"><h2>${prev ? "B against A" : "A: the prompt as received"}</h2><div class="sub">${!prev ? "This is the prompt as received. Later versions show what they changed." : diffNote}</div><div style="margin-top:12px">${diffHtml}</div>
      <details style="margin-top:12px"><summary style="cursor:pointer;font-weight:500">Show the full prompt ${esc(sel.id)}</summary><textarea readonly class="prompt-box" rows="14" style="margin-top:8px" aria-label="Full prompt ${esc(sel.id)} (read-only)">${esc(selText)}</textarea></details></div>
    <h2 style="font-size:16px;font-weight:600;color:var(--navy);margin:24px 0 12px">Ready to test</h2><div class="grid g2">${cands.map(c => `<div class="card"><div style="display:flex;justify-content:space-between;gap:8px"><h3>${esc(c.name)}</h3></div><p class="sub">${c.variables.ok ? "✓ every template variable kept" : "✕ drops " + esc(c.variables.dropped.join(", "))}${c.lint_before != null ? ` · contradictions ${c.lint_before} → ${c.lint_after}` : ""} ${info("fingerprint " + c.hash)}</p><div class="actions" style="margin-top:12px"><button class="btn sm primary" data-test="${esc(c.key)}">Create experiment</button></div></div>`).join("")}</div>`;
  $$("tr[data-ver]", el).forEach(r => r.onclick = ev => { if (!ev.target.closest("a,button")) go("library", r.dataset.ver); });
  $$("[data-roll]", el).forEach(b => b.onclick = ev => { ev.stopPropagation(); const x = P.versions.find(q => q.id === b.dataset.roll); if (x.expView) { const dd = dyn(byId(x.expId)); dd.rolledBack = true; } else DYN.libRolled.push(x.id);
    const to = P.versions[P.versions.findIndex(q => q.id === x.id) - 1]; DYN.libLog.push({ ts: x.time || new Date().toISOString(), type: "Rolled back", text: `Rolled back ${x.id} (${x.hash.slice(0, 7)}) to ${to.id} (${to.hash.slice(0, 7)}) from the Prompt Library; callers hear ${to.id} again.`, exp: x.from }); saveDyn(); toast(`Rolled back to ${to.id}. Logged in the Decision Log.`); route(); });
  $$("[data-test]", el).forEach(b => b.onclick = () => { const c = cands.find(x => x.key === b.dataset.test); startWizard({ name: c.name, change: c.name, promptB: fullPromptB(c.key) }); });
};

/* ------------------------------------------------------------------ Decision Log */
const LF = DYN.ui.log || { q: "", type: "all", exp: "all", page: 0 };
ROUTES.log = (el) => {
  const evs = allEvents().filter(x => (LF.type === "all" || x.type === LF.type) && (LF.exp === "all" || x.id === LF.exp) && (!LF.q || (x.text + x.exp + x.type).toLowerCase().includes(LF.q.toLowerCase())));
  const PG = 12, pages = Math.max(1, Math.ceil(evs.length / PG)); LF.page = Math.min(LF.page, pages - 1);
  const rows = evs.slice(LF.page * PG, LF.page * PG + PG), exps = EXPS().filter(e => eventsFor(e).length);
  el.innerHTML = head("Decision Log", `Every event with its time and reason, in a tamper-evident record. ${info("Events from the engine carry the first characters of their hash in the record. Pause, stop and library rollbacks are actions of this console and are labelled as such. Hover a reason for the full text and its hash.")}`, `<button class="btn" id="l-csv">Export CSV</button>`) +
    `<div class="filters"><div class="field grow"><label for="l-q">Search</label><input type="search" id="l-q" value="${esc(LF.q)}" placeholder="Reason, test or event"></div><div class="field"><label for="l-type">Event</label><select id="l-type"><option value="all">All events</option>${EV_TYPES.map(t => `<option ${LF.type === t ? "selected" : ""}>${t}</option>`).join("")}</select></div>
      <div class="field"><label for="l-exp">Test</label><select id="l-exp"><option value="all">All tests</option>${exps.map(e => `<option value="${esc(e.id)}" ${LF.exp === e.id ? "selected" : ""}>${esc(e.record.config.name)}</option>`).join("")}</select></div></div>
    ${rows.length ? `<div class="tbl-wrap"><table><thead><tr><th>Time</th><th>Test</th><th>Event</th><th>Reason</th></tr></thead><tbody>${rows.map(x => `<tr><td style="white-space:nowrap">${esc(fdt(x.ts))}</td><td>${x.id ? `<a href="#/experiments/${encodeURIComponent(x.id)}">${esc(x.exp)}</a>` : esc(x.exp)}</td><td>${pill(x.type, { Saved: "plain", Started: "run", "Harm alert": "neg", "Split alert": "warn", Stopped: "neg", Promoted: "pos", Approved: "pos", Rejected: "plain", "Rolled back": "warn", Held: "warn", Inconclusive: "plain", Holdback: "run", Paused: "plain", Resumed: "run" }[x.type])}</td><td class="muted reason" title="${esc(x.text + (x.hash ? " · record " + x.hash : " · console action"))}">${esc(x.text.length > 120 ? x.text.slice(0, 117) + "..." : x.text)}</td></tr>`).join("")}</tbody></table></div>
      <div class="pager"><span>${evs.length} event${evs.length === 1 ? "" : "s"}</span><span><button class="btn sm" id="l-prev" ${LF.page ? "" : "disabled"}>Previous</button> Page ${LF.page + 1} of ${pages} <button class="btn sm" id="l-next" ${LF.page < pages - 1 ? "" : "disabled"}>Next</button></span></div>` : `<div class="empty">No events match.</div>`}
`;
  const save = () => { DYN.ui.log = LF; saveDyn(); };
  $("#l-q").oninput = ev => { LF.q = ev.target.value; LF.page = 0; save(); clearTimeout(window.__lq); window.__lq = setTimeout(() => { const p = ev.target.selectionStart; route(); const n = $("#l-q"); n.focus(); n.setSelectionRange(p, p); }, 250); };
  $("#l-type").onchange = ev => { LF.type = ev.target.value; LF.page = 0; save(); route(); }; $("#l-exp").onchange = ev => { LF.exp = ev.target.value; LF.page = 0; save(); route(); };
  const pv = $("#l-prev"), nx = $("#l-next"); if (pv) pv.onclick = () => { LF.page--; save(); route(); }; if (nx) nx.onclick = () => { LF.page++; save(); route(); };
  $("#l-csv").onclick = () => download("canary_decision_log.csv", toCsv(["time", "test", "event", "reason", "record_hash"], evs.map(x => [x.ts, x.exp, x.type, x.text, x.hash])));
};

/* ------------------------------------------------------------------ Settings */
/** The data files the custom metric builder reads its columns from, and the Rescan button (the local server re-reads the folder). */
function dataFilesHtml() {
  const fc = FCAT(), types = f => { const n = {}; fc.columns.filter(c => c.file === f.file).forEach(c => { n[c.type] = (n[c.type] || 0) + 1; }); return Object.entries(n).map(([t, k]) => `${k} ${t}`).join(" · "); };
  return `<div class="sec-row" style="margin-top:16px"><div><h3>Data files</h3><div class="sub">The columns the custom metric builder offers, read from the files in the resources folder${fc.scanned_at ? `; scanned ${esc(fdt(fc.scanned_at))}` : ""}.</div></div>${LIVE ? `<button class="btn sm" id="s-rescan">Rescan files</button>` : `<span class="note">Rescan needs the local server (./start.sh)</span>`}</div>
    ${fc.files.length ? `<div class="tbl-wrap" style="margin-top:8px"><table><thead><tr><th>File</th><th class="num">Rows</th><th>Linked to calls by</th><th>Columns by type</th></tr></thead><tbody>${fc.files.map(f => `<tr><td><b>${esc(f.file)}</b></td><td class="num">${f.rows == null ? "-" : nf(f.rows)}</td><td>${f.linkable === false ? pill("Can't be linked to calls", "neg") : esc([f.keys && f.keys.call, f.keys && f.keys.lead].filter(Boolean).join(", "))}</td><td class="note">${esc(types(f))}</td></tr>`).join("")}</tbody></table></div>` : `<p class="note">No data files found${fc.missing ? ` in ${esc(fc.missing)}` : ""}.</p>`}`;
}
ROUTES.settings = (el) => {
  const s = SET(), running = EXPS().filter(e => view(e).running);
  const f = (id, label, input, hint) => `<div class="field"><label for="${id}">${label}${hint ? ` <span class="hint">${hint}</span>` : ""}</label>${input}</div>`;
  const mrows = allMetrics();
  el.innerHTML = head("Settings", "What the autopilot may do, and the defaults new tests start from.") + autopilotCard() +
    fold(`Metric list`, `<div class="sub">Every metric a test can use as its primary goal, a guardrail or a secondary metric: the formula in plain words, which way is better, and today's value (last 30 days, all traffic). Custom metrics saved from New Experiment appear here and can be reused.</div>
      <div class="tbl-wrap" style="margin-top:12px"><table><thead><tr><th>Metric</th><th>Group</th><th>Formula</th><th>Direction</th><th class="num">Today</th><th>Note</th><th></th></tr></thead><tbody>${mrows.map(m => `<tr><td><b>${esc(m.name)}</b><div class="mono muted">${esc(m.key)}</div></td><td>${pill(m.group || "Custom", m.group === "Outcome" ? "run" : m.group === "Custom" ? "pos" : "plain")}</td><td style="max-width:320px">${esc(metricWords(m))}</td><td>${m.direction === "lower" ? "↓ lower is better" : "↑ higher is better"}</td><td class="num">${m.available === false ? pill("Not in data yet", "plain") : fmtMetric(metricEval(m, null).value, m)}</td><td class="muted" style="max-width:260px">${esc(m.note || (m.custom ? "Custom metric" : ""))}</td><td>${m.custom ? `<button class="btn sm" data-mrm="${esc(m.key)}">Remove</button>` : ""}</td></tr>`).join("")}</tbody></table></div>${dataFilesHtml()}`, `${mrows.length} metrics a test can use`, false, "s-metrics") + `
    ` + fold(`Variable catalog`, `<div class="sub">Every variable the bot can receive, built once from the data and editable here. The router, the segment builder and the balance check all read this one list. Only variables known before the call can pick leads.</div>
      <div class="tbl-wrap" style="margin-top:12px"><table><thead><tr><th>Variable</th><th>Meaning</th><th>Type</th><th>Allowed values (synthetic mix)</th><th>Known before the call?</th></tr></thead><tbody>${CAT().variables.map(v => `<tr><td><b>${esc(v.label)}</b><div class="mono muted">${esc(v.name)}</div></td><td>${esc(v.meaning)}</td><td>${esc(v.type)}</td><td>${v.values.length ? v.values.map((x, i) => `<span class="tag">${esc(x)}${v.mix ? " " + Math.round(v.mix[i] * 100) + "%" : ""}</span>`).join(" ") : '<span class="muted">any number</span>'}</td><td>${v.mix ? `<label class="chk"><input type="checkbox" data-pre="${esc(v.name)}" ${(SET().preCallOff || []).includes(v.name) ? "" : "checked"}> ${(SET().preCallOff || []).includes(v.name) ? "No: cannot pick leads" : "Yes: can pick leads"}</label>` : `${pill("No: decided during the call", "plain")}`}</td></tr>`).join("")}</tbody></table></div><p class="note" style="margin-top:8px">${esc(CAT().note)}</p>`, `${CAT().variables.length} variables, and which can pick leads`, false, "s-catalog") + `
    <div class="grid g2"><div class="card"><h2>Defaults for new tests</h2><div class="sub">Used to fill in New Experiment. The four demo tests were set up with these defaults.</div><div class="form-grid" style="margin-top:16px">
        ${f("s-conf", "Confidence", `<select id="s-conf">${[0.9, 0.95, 0.99].map(x => `<option value="${x}" ${s.confidence === x ? "selected" : ""}>${x * 100}%</option>`).join("")}</select>`)}${f("s-harm", "Harm threshold", `<select id="s-harm">${[0.99, 0.995, 0.999].map(x => `<option value="${x}" ${s.harm_bar === x ? "selected" : ""}>${(x * 100).toFixed(1)}%</option>`).join("")}</select>`, "daily check")}
        ${f("s-min", "Minimum leads per arm before any decision", `<input type="number" id="s-min" value="${s.min_leads_per_arm}">`)}${f("s-days", "Test length", `<select id="s-days">${[7, 14, 21, 28].map(d => `<option value="${d}" ${s.window_days === d ? "selected" : ""}>${d} days</option>`).join("")}</select>`, "7 to 28, whole weeks")}${f("s-share", "Share to B (%)", `<input type="number" id="s-share" value="${Math.round(s.share_b * 100)}">`)}${f("s-lift", "Expected lift (% of A's rate)", `<input type="number" id="s-lift" value="${Math.round((s.lift_rel || 0.1) * 100)}">`, "default +10%")}${f("s-dur", "Call-duration limit (%)", `<input type="number" id="s-dur" value="${Math.round(s.duration_margin * 100)}">`)}
        ${f("s-lpd", "Leads per day, all traffic", `<input type="number" id="s-lpd" value="${s.leads_per_day}">`, "an assumption")}${f("s-appr", "Approval mode", `<select id="s-appr"><option value="auto" ${s.approval === "auto" ? "selected" : ""}>Automatic</option><option value="manual" ${s.approval === "manual" ? "selected" : ""}>Manual: a person approves every win</option></select>`, "both paths are logged")}</div>
        <p class="note" style="margin-top:12px">${esc(C.defaults.leads_per_day_note)}</p><div class="actions" style="margin-top:12px"><button class="btn primary" id="s-save">Save defaults</button></div></div>
      <div class="grid"><div class="card"><h2>Overlap warning</h2><div class="sub">When two running tests include the same leads, their results interfere. A launch is refused if it would overlap a running one.</div><div style="margin-top:12px">${(() => { const m = runningMain(), c = m.flatMap((x, i) => m.slice(i + 1).filter(y => segsOverlap(segOf(x) || {}, segOf(y) || {})).map(y => [x, y])); return c.length ? `<div class="banner warn" style="margin:0"><div><b>Overlap.</b> ${c.map(([x, y]) => esc(x.record.config.name) + " and " + esc(y.record.config.name)).join("; ")} share leads. Finish one before trusting the other.</div></div>` : `<div class="banner pos" style="margin:0"><div><b>No overlap.</b> ${m.length} test${m.length === 1 ? "" : "s"} launched here ${m.length === 1 ? "is" : "are"} running. The five pre-set scenarios are separate replays of history and are exempt.</div></div>`; })()}</div></div>
        <div class="card"><h2>Tools</h2><div class="sub">For engineers and for the optional extras.</div><div class="actions" style="margin-top:12px"><a class="btn" href="#/import">Import results files</a>${HOSTED ? '<span class="note">Proof lab, call labelling and audio are not in the hosted copy (they use real-call data). Run ./start.sh locally for them.</span>' : `<a class="btn" href="${LIVE ? "/tools.html" : "canary_tools.html"}">Proof lab, label calls, hear it</a>`}</div></div>
        <div class="card"><h2>This demo</h2><div class="sub">What is real and what is simulated.</div><ul style="margin:8px 0 0;padding-left:20px;font-size:13px"><li>The demo tests use <b>simulated</b> outcomes with a known injected effect.</li><li>Call lengths are resampled from 713 <b>real</b> recordings.</li><li>Leads per day is an <b>assumption</b> (no real volume was provided).</li><li>History holds re-runs of our scenarios and sample result files.</li><li>${STORE.on ? "Launched tests, days played, approvals and rollbacks are saved in the history database on this server." : "Days played, approvals and rollbacks live in this browser only."}</li></ul><div class="actions" style="margin-top:12px"><button class="btn danger" id="s-reset">Reset the demo</button></div></div>${storeCard()}</div></div>`;
  const setAp = () => { DYN.settings = { ...DYN.settings, autopilot: { rollback: $("#ap-roll").checked, held: $("#ap-held").checked } }; saveDyn(); toast("Autopilot updated."); };
  $("#ap-roll").onchange = setAp; $("#ap-held").onchange = setAp;
  $("#s-save").onclick = () => { DYN.settings = { ...DYN.settings, confidence: +$("#s-conf").value, harm_bar: +$("#s-harm").value, min_leads_per_arm: +$("#s-min").value, window_days: +$("#s-days").value, share_b: +$("#s-share").value / 100, duration_margin: +$("#s-dur").value / 100, leads_per_day: +$("#s-lpd").value, approval: $("#s-appr").value, lift_rel: +$("#s-lift").value / 100 }; DYN.settings.mde = Math.round(SET().baseline * DYN.settings.lift_rel * 10000) / 10000; saveDyn(); WZ = null; toast("Defaults saved. New experiments will start from them."); };
  const rs = $("#s-rescan", el); if (rs) rs.onclick = async () => { rs.disabled = true; rs.textContent = "Scanning..."; try { const r = await fetch("/api/filecatalog/rescan", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const j = await r.json(); if (!r.ok || !j.columns) throw new Error(j.error || "rescan failed"); C.file_catalog = j; toast(`${j.files.length} file${j.files.length === 1 ? "" : "s"}, ${j.columns.length} columns.`); } catch (err) { toast("Could not rescan: " + (err.message || err)); } refresh(); };
  $$("[data-mrm]", el).forEach(b => b.onclick = () => { DYN.settings = { ...DYN.settings, customMetrics: customMetrics().filter(m => m.key !== b.dataset.mrm) }; saveDyn(); toast("Removed from the metric list. Tests already launched keep their locked copy."); route(); });
  $$("[data-pre]", el).forEach(c => c.onchange = () => { const off = new Set(SET().preCallOff || []); c.checked ? off.delete(c.dataset.pre) : off.add(c.dataset.pre); DYN.settings = { ...DYN.settings, preCallOff: [...off] }; saveDyn(); route(); });
  $("#s-reset").onclick = async () => {
    if (!confirm(STORE.on ? "Reset the demo? Launched tests, days played, approvals, rollbacks, drafts and saved settings are cleared from the history database, for every browser on this server. The click log keeps a 'reset' entry." : "Reset the demo? Days played, approvals, rollbacks and launched tests are cleared.")) return;
    if (STORE.on) { try { const r = await fetch("/api/store/reset", { method: "POST", headers: { "X-Canary-Store": "1" }, body: "{}" }); if (!r.ok) throw new Error(r.status); } catch (e) { toast(`Could not reset the history database (${e.message || e}). Nothing was cleared.`, 6000); return; } STORE.on = false; }
    try { localStorage.removeItem(SK); } catch { } location.hash = "#/overview"; location.reload(); };
  if (STORE.on) fetch("/api/store/info").then(r => r.json()).then(j => { if (j.error) return; STORE.info = j; const c = $("#s-store"); if (c) c.outerHTML = storeCard(); }).catch(() => { });
};
/** Settings: what the autopilot may do on its own. Each action it takes is a pre-chained entry of the decision record. */
function autopilotCard() {
  const ap = AP();
  return `<div class="card" id="s-autopilot" style="margin-bottom:16px"><div class="sec-row"><h2>Autopilot</h2>${pill("on", "pos")}</div><div class="sub">Picky already stops a clearly worse B and promotes a winner by itself. Two more things it can do without waiting for a person:</div>
    <div style="display:grid;gap:8px;margin-top:12px"><label class="chk"><input type="checkbox" id="ap-roll" ${ap.rollback ? "checked" : ""}> <span><b>Roll back by itself</b> when the week after a promotion (the ${pct(SET().holdback || 0.05, 0)} holdback) shows B clearly below A</span></label>
      <label class="chk"><input type="checkbox" id="ap-held" ${ap.held ? "checked" : ""}> <span><b>Keep A by itself</b> when a held win (it broke a guardrail) gets no answer within ${heldDays()} days</span></label></div>
    <p class="note" style="margin-top:8px">Each action is written to the hash-chained decision record, like a person's click. For results files Picky only advises.</p></div>`;
}
/** Settings: where the history is kept, how much is in it, and the file itself. */
function storeCard() {
  if (!STORE.on) return "";
  const i = STORE.info || {}, t = i.tests || {}, n = k => nf(t[k] || 0);
  return `<div class="card" id="s-store"><h2>History database</h2><div class="sub">Every test, its locked setup, day-by-day results, decision record and every click, in one SQLite file on this server.</div>
    <table style="margin-top:8px;font-size:13px"><tbody><tr><td>Tests launched here</td><td class="num"><b>${nf((t.launched || 0) + (t.files || 0))}</b></td></tr><tr><td>Demo tests and History samples</td><td class="num">${n("demo")} + ${n("sample")}</td></tr><tr><td>Clicks logged</td><td class="num">${nf(i.actions || 0)}</td></tr><tr><td>Decision record entries</td><td class="num">${nf(i.decision_entries || 0)}</td></tr></tbody></table>
    <p class="note" style="margin-top:8px">File: <span class="mono">${esc(i.path || "data/history.db")}</span> · ${esc(i.engine || "SQLite")}</p>
    <div class="actions" style="margin-top:8px"><a class="btn" href="/api/store/download" download>Download the database</a></div></div>`;
}
